version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - netconn
  test-db:
    image: postgres:13
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - netconn
  prod-db:
    image: postgres:13
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: chuser
      POSTGRES_PASSWORD: chutangermed6
      POSTGRES_DB: emploi
    networks:
      - netconn 
    volumes:
      - myapp:/var/lib/postgresql/data

networks:
 netconn:
volumes:
  myapp:
